### ISSUE TITLE
Streamline events pipeline

### ISSUE THREAD

**Issue by NDStrahilevitz** [aquasecurity/tracee#1684]
## Prerequisites

- [x] Is this an EPIC issue describing other issues ? (add label: EPIC)
- [ ] I'm going to create a PR to solve this (assign to yourself)
- [ ] Someone else should solve this.

## Feature description

This an epic which may include bug fixes and features, but probably mostly refactors.

## Context

Currently, the ebpf package is structured to use a pipeline, where channels are passed to pipeline function which return other channels:

<img width="1458" alt="image" src="https://user-images.githubusercontent.com/7395852/166618159-38baa8a8-7066-4d38-904b-f42c2f2d4756.png">

However, there is no formal abstraction for this besides a convention set by the code. Some problems that arise from this, for example:

1. The output buffers may vary in size between the pipeline functions.
2. Pipeline function signatures may change between pipeline stages
3. The pipeline passes a `trace.Event` and a gocontext, however we may require additional **defined** context between pipeline steps

I'm suggesting to refactor this part as part of the ongoing "stabilization" effort, and possibly move the pipeline to it's own `pipeline` package, which can then be used alongside a separated `events` package.

In addition, the pipeline should be able to easily process events from various eBPF buffers (for example the network event buffer)

## Additional

PR: #1689 (pipeline: split process and sink stages)

**Comment by yanivagman** [comment]
This issue can be closed in favor of the following 2 issues:

1. #3254 is about extracting pipeline to its own package
2. As part of #2870 we will create an internal pipeline struct that will embed trace.Event in it and some extra internal fields (e.g. timeInPipeline). Also see this comment https://github.com/aquasecurity/tracee/issues/2870#issuecomment-1570919351
