### ISSUE TITLE
Tracee-eBPF Configuration API

### ISSUE THREAD

**Issue by NDStrahilevitz** [aquasecurity/tracee#1725]
## Prerequisites

- [x] This issue is an EPIC issue (add label: EPIC).
- [ ] This issue is an EPIC TASK (add issue to EPIC description).

Select one OR another:

- [x] I'll create a PR to implement this feature (assign to yourself).

## Feature description

In order to allow configuration of tracee-ebpf during runtime, for example to change filters, an API definition is required to communicate to tracee-ebpf.
This API can then be implemented through gRPC, HTTP or any other integration method deemed appropriate.

## Additional Information (feature drawings, files, logs, etc)

#1726: The initial feature of this API will be a filter configuration API.

**Comment by yanivagman** [comment]
Dup of #636
