### ISSUE TITLE
[FEAT] workflows should include static checking and style enforcement

### ISSUE THREAD

**Issue by rafaeldtinoco** [aquasecurity/tracee#1733]
## Prerequisites

- [x] This issue is an EPIC issue (add label: EPIC).
- [ ] This issue is an EPIC TASK (add issue to EPIC description).

Select one OR another:

- [x] I'll create a PR to implement this feature (assign to yourself).
- [ ] Someone else should implement this (describe it well).

## Feature description

This feature is about changing PR workflows and tests to enforce styling and code checking. The feature is needed because we currently have no defined style guidelines for Go or C, and we currently don't do static checking during PRs.

## Additional Information (feature drawings, files, logs, etc)

1. PR: https://github.com/aquasecurity/tracee/pull/1734
