### ISSUE TITLE
Last tasks for Milestone 0.8.0

### ISSUE THREAD

**Issue by rafaeldtinoco** [aquasecurity/tracee#1854]
- [x] Address issues from Milestone https://github.com/aquasecurity/tracee/milestone/18
- [x] Make sure enrichment is working for k8s
- [x] Check enrichment feature performance (throughput)
  - [x] https://github.com/aquasecurity/tracee/issues/1873
  - [x] https://github.com/aquasecurity/tracee/issues/1872
  - [x] https://github.com/aquasecurity/tracee/pull/1902
- [x] #1884
- [x] Enable enrichment feature in tracee entrypoint (for end user)
- [x] Check documentation fully and prepare release notes
- [x] Remove noisy signatures (by default)
  - [x] https://github.com/aquasecurity/tracee/issues/1483
  - [x] https://github.com/aquasecurity/tracee/pull/1916
- [x] To have Go-CEL POC merged (as tech preview)
- [x] Merge https://github.com/aquasecurity/tracee/pull/1820
- [x] Upgrade libbpfgo to latest (with libbpf v0.8) @grantseltzer 
- [x] https://github.com/aquasecurity/tracee/pull/1908
- [x] Fully test BTFHUB capable binary in a non BTF enabled kernel
- [x] Make sure ALL TESTS are passing at the time of the release

**Comment by NDStrahilevitz** [comment]
So about the container enrichment goals:
1. For enabling enrichment in the entrypoint, I think the best solution currently would be mounting `/var/run` in the docker command since that is where our autodiscover currently searches, WDYT?
2. About documentation, i've initially added some in `docs/integrations.md`, I think best option is either linking to it from somewhere else more visible, or giving it a whole separate page. Maybe there's room to expand there as well (see next point).
3. So I can say from my dev tests (and from fixing bugs discovered in the feature through k8s), this should work in k8s.
Main blockers from smooth integrations is mounting the correct socket, that should probably be expanded on in docs and maybe later we can add better autodiscover support (I'll open an issue on that, but I don't think it should be part of this milestone).
4. I'll try to report on performance effect in the next few days, but I will check it in a CNDR like env.

**Comment by rafaeldtinoco** [comment]
> * For enabling enrichment in the entrypoint, I think the best solution currently would be mounting `/var/run` in the docker command since that is where our autodiscover currently searches, WDYT?

That exposes lots of things from host, we should try to stick to only container engine sockets I believe.

**Comment by rafaeldtinoco** [comment]
> * About documentation, i've initially added some in `docs/integrations.md`, I think best option is either linking to it from somewhere else more visible, or giving it a whole separate page. Maybe there's room to expand there as well (see next point).

Yep, I was thinking more of the documentation when the feature is fully integrated to what user sees (the docker container run cmd). It depends on what we decide in the previous comment I suppose.

**Comment by rafaeldtinoco** [comment]
> 4\. I'll try to report on performance effect in the next few days, but I will check it in a CNDR like env.

I'm adding a TODO for me to do the same in tracee's side (so we can compare, like we did before when doing it for the first time).

**Comment by NDStrahilevitz** [comment]
> That exposes lots of things from host, we should try to stick to only container engine sockets I believe. At the same time, we are running tracee in a privileged container already, still... I believe you know what I mean... =\

Ok, so just expose the autodiscovered paths for now, and we can improve this feature later (i've outlined some ideas in #1864).
So either we add a flag to the entrypoint to override for unsupported sockets in the autodiscover (because we can't add ebpf flags to the entrypoint unless we're running ebpf only), or we document that currently only these paths are supported out of the box for "full" tracee.

**Comment by rafaeldtinoco** [comment]
> Ok, so just expose the autodiscovered paths for now, and we can improve this feature later (i've outlined some ideas in #1864).

> So either we add a flag to the entrypoint to override for unsupported sockets in the autodiscover (because we can't add ebpf flags to the entrypoint unless we're running ebpf only), or we document that currently only these paths are supported out of the box for "full" tracee.

For the tracee docker container experience (without k8s deployment) I believe we will, definitely, need a "docker run" wrapper (and I'll work on that in near future, already have plans for it).

For now, maybe we could "teach" how to bind mount needed sockets (in the docker run cmdline) to the tracee docker container and give the default places as cmdline example.

**Comment by NDStrahilevitz** [comment]
> For now, maybe we could "teach" how to bind mount needed sockets (in the docker run cmdline) to the tracee docker container and give the default places as cmdline example.

So I checked and that's what we show in `docs/integrations.md`, how to mount the sockets through `-v` flags in the docker run command.

**Comment by rafaeldtinoco** [comment]
> > For now, maybe we could "teach" how to bind mount needed sockets (in the docker run cmdline) to the tracee docker container and give the default places as cmdline example.
> 
> So I checked and that's what we show in `docs/integrations.md`, how to mount the sockets through `-v` flags in the docker run command.

Yep, that is definitely not the best place for the end user to learn how to use the feature. I'll probably move it, increment it a bit and index it in mkdocs index so readers can access that information more easily. Thanks for checking.

**Comment by NDStrahilevitz** [comment]
Marking "Enable enrichment feature in tracee entrypoint (for end user)" as done since the feature flag was merged.

**Comment by rafaeldtinoco** [comment]
DONE
