### ISSUE TITLE
k8s user experience

### ISSUE THREAD

**Issue by josedonizetti** [aquasecurity/tracee#2050]
## Prerequisites

- [X] This issue is an EPIC issue (add label: EPIC).
- [ ] This issue is an EPIC TASK (add issue to EPIC description).

Select one OR another:

- [X] I'll create a PR to implement this feature (assign to yourself).
- [ ] Someone else should implement this (describe it well).

## Feature description

Improve tracee user experience on kubernetes. 

- [x] https://github.com/aquasecurity/tracee/issues/3118
- [x] Remove postee
- [x] Add base policy with config map](https://github.com/aquasecurity/tracee/issues/3129)
- [x] https://github.com/aquasecurity/tracee/issues/2102
- [x] https://github.com/aquasecurity/tracee/issues/2113
- [x] https://github.com/aquasecurity/tracee/issues/2114
- [x] https://github.com/aquasecurity/tracee/issues/2138
- [x] enable k8s enrichment by default (https://github.com/aquasecurity/tracee/issues/2731)
- [x] https://github.com/aquasecurity/tracee/issues/3119

**Comment by josedonizetti** [comment]
Rego configuration -> https://github.com/aquasecurity/tracee/discussions/2402
