### ISSUE TITLE
[FEAT] add unit tests to tracee-ebpf params parsing done by tracee-rules

### ISSUE THREAD

**Issue by AsafEitani** [aquasecurity/tracee#2196]
## Prerequisites

- [x] This issue is an EPIC issue (add label: EPIC).
- [ ] This issue is an EPIC TASK (add issue to EPIC description).

Select one OR another:

- [ ] I'll create a PR to implement this feature (assign to yourself).
- [x] Someone else should implement this (describe it well).

## Feature description

This feature is about adding unit tests to the argument parsing in tracee-rules:
[pkg/events/parse/params.go](https://github.com/aquasecurity/tracee/blob/main/pkg/events/parse/params.go)

The feature is needed to make sure those functions work properly.

**Comment by ShubhamPalriwala** [comment]
Hey @AsafEitani, have been exploring the eBPF space recently, can I take this up to just use this as a reason to start my deep dive?

**Comment by josedonizetti** [comment]
@ShubhamPalriwala Yes you can take. This task is based on the comment of this PR https://github.com/aquasecurity/tracee/pull/2186#discussion_r977932298
