### ISSUE TITLE
Everything is an event

### ISSUE THREAD

**Issue by josedonizetti** [aquasecurity/tracee#2355]
## Feature description

This epic represents the new tracee experience, where we will have a single binary, every thing will be an event. The idea is to implement this feature incrementally to avoid a HUGE pr complicating the review process. 

Please add as an item to the list for any bug, refactor, change found for the new tracee binary.

## TODO

- [x] fix filtering (eg: `tracee --trace set=rules`)
- [x] fix errors when loading same signature in more than one scope
- [x] add shortcuts (eg: `tracee --trace e=fileless_execution`)
- [x] rules events not aligned
- [x] add signature events metada (#2541)
- [x] signature events should be multiscoped ( ./dist/tracee --trace 1:event=anti_debugging --trace 2:event=anti_debugging), should print twice, once per scope
- [x] finding.Data should an arguments of signature events
- [x] multiple printers
- [x] make tracee binary the default for tracee image
- [x] make signature events load by default
- [x] add webhook support
- [x] fix k8s yamls to use tracee binary
- [x] remove helm flag everythingIsAnEvent
- [x] make sure postee integration works
- [x] make sure falcosidekiq integration works
- [x] documentation

A few TODOs from the original PR that we agreed on implementing on the next release 0.11.0
- [x] https://github.com/aquasecurity/tracee/pull/2439#discussion_r1045165063
- [x] https://github.com/aquasecurity/tracee/pull/2439#discussion_r1045227985
- [x] https://github.com/aquasecurity/tracee/pull/2439#discussion_r1045164237
- [x] https://github.com/aquasecurity/tracee/pull/2439#discussion_r1045144380
- [x] https://github.com/aquasecurity/tracee/pull/2439#discussion_r1043547108

**Comment by josedonizetti** [comment]
1 - extract tracee-rules logic
2 - add signatures as events
3 - add template as a printer option
4 - add webhook as a printer oprion

**Comment by josedonizetti** [comment]
- add webhook support
- fix filtering
- add shortcuts (eg: `tracee --tracee e=fileless_execution`)
- refactor events printer
- rules events no aligned
-

**Comment by itaysk** [comment]
another TODO here: 
if I create a "signature" (now just an event), I'm expecting to filter it just like every event, including argument filters. For example, I created a `file_write` signature based on `security_file_open`, and I wanted to filter `file_write.args.pathname=/something` which didn't work.

**Comment by josedonizetti** [comment]
Problem 1:
---
Currently, when `tracee` (single binary) creates an event from a signature, it uses almost all the information from the original event (eg: ptrace), and ignores the information from the signature (eg: [anti_debugging Metatada/Data](https://github.com/aquasecurity/tracee/blob/main/signatures/golang/anti_debugging_ptraceme.go#L23-L39)). 

One of the TODOs above is about not using the original event's arguments, but instead using the signatures [`Data`](https://github.com/aquasecurity/tracee/blob/main/signatures/golang/examples/example.go#L59-L61).

So, instead of this:

```
"args":[
  {"name":"request","type":"string","value":"PTRACE_TRACEME"},
  {"name":"pid","type":"pid_t","value":0},
  {"name":"addr","type":"void*","value":"0x0"},
  {"name":"data","type":"void*","value":"0x0"}
 ]
```

we would have:

```
"args":[
  {"name":"severity","type":"string","value": "HIGH"},
  {"name":"count","type":"int","value":1},
 ]
```

This makes sense to me, one problem is that we only know the "fields" names for finding.Data once the signature is executed, so we can't actually define an `Argument` for the event when booting tracee. Which breaks events definition.

Problem 2: 
---

Besides `finding.Data`, another important piece of information from the signatures is its [metadata](https://github.com/aquasecurity/tracee/issues/2541), which needs to be printed along with the signature event. And  it should also be [filterable](https://github.com/aquasecurity/tracee/issues/532#issuecomment-1420300088). (eg: only `severity=HIGH`)


Proposal:
---

I thought about solving those problems, along with two other `TODOs` listed in the description by extending argument filters, and using both the data and properties of a signature as arguments, for example:


for signature events, arguments are a combination of `data`, and `properties` from the metadata:
```
"args":[
{"name":"data","type":"map[string]interface{}","value":{"key1":"val1","key2":"val2"}},

{"name":"properties","type":"map[string]interface{}","value":{"Category":"defense-evasion","Kubernetes_Technique":"","Severity":1,"Technique":"Debugger Evasion","external_id":"T1622","id":"attack-pattern--e4dc8c01-417f-458d-9ee0-bb0617c1b391"}}
]
```

and then add a specific syntax to use the argument filter:

```
tracee --trace anti_debugging.args.data[key]=value --trace anti_debugging.args.properties[key]=value
```
This solves both problems, where we have the `finding.Data` as arguments instead of the original arguments of the event, they can be filtered, even though we don't know what fields the signature will have inside the data, because for the event definition it only matters the map definition `argument: data type: map`, also fixes the problem 2, adding the metadata and allowing it to be filtered. 

Thoughts?

@yanivagman 
@itaysk 
@rafaeldtinoco 
@NDStrahilevitz 
@geyslan

**Comment by rafaeldtinoco** [comment]
Spoke to @josedonizetti a little bit about his comment. I do agree to all he proposed and thought a little bit out loud with him in private. The things we discussed were:

1. should the argument be a map[]interface{} ? who is the consumer ? would that be ok for them ? if not, then creating a type and/or arguments per signature event would be needed.

2. if the args are a map, then maybe another arg filter should be used (or another filter type if needed) and, maybe, use `.sigs.` instead of `.args.`. Not sure this is really needed, but could help in distinguishing the difference for the signature events (as they are not arguments per see).

Anyway, just thinking out loud and giving 2 cents.

**Comment by itaysk** [comment]
To me args == data. the name `args` is a legacy from the syscall tracing roots of Tracee, and it's lost it's relevancy (as a name) when we started doing kprobes and extracting "our" data with events. So I think we should rename `args` to `data` (doesn't have to be now) and that will easily map into signature events, as well as kprobes.

signature metadata is an interesting one. Intuitively I don't think it belongs in `data`. Let's metadata is handles in other event types we have today:
1. syscalls - the metadata is in the man pages. we don't explain what is `execve` we trust the user will look it up.
2. kprobes/custom events - metadata is [in the docs](https://github.com/aquasecurity/tracee/tree/main/docs/contributing/events).

Note that "metadata" above doesn't include basic fields like event name/id which are pulled into the event's `context`.

So my suggestion:
1. signature data -> event `args` (should be `data` at some point)
2. signature basic metadata -> event `context`
3. signature metadata -> documentation

One exception is the `severity` field which I think we should promote to a context level field.

**Comment by itaysk** [comment]
I may have had too idealistic view of current state. I just realized that container enrichment is shoved into args as well. Not sure how to reconcile that.

**Comment by rafaeldtinoco** [comment]
> One exception is the `severity` field which I think we should promote to a context level field.

In the past we've discussed events should have "priority" (maybe severity ?) so we could stop sending them to userland depending on the perf buffer bandwidth. Maybe the same context "field" could be used for signature events (as well as kernel events).

**Comment by josedonizetti** [comment]
🎉

**Comment by yanivagman** [comment]
🎉
