### ISSUE TITLE
Improve events documentation

### ISSUE THREAD

**Issue by yanivagman** [aquasecurity/tracee#2809]
We recently exposed some events documentation in https://aquasecurity.github.io/tracee/v0.12/docs/events/overview/
Hoever, there are still a few places to improve:

- [ ] Add documentation for missing events (#2901)
- [ ] Enforce DocPath existance in events definition when adding new events (https://github.com/aquasecurity/tracee/pull/1808#issuecomment-1161755558)
- [ ] Expose documentation from CLI (#436)
- [ ] Document event schema once stabilized (#2870 )

**Comment by itaysk** [comment]
also need to document the event schema once it's stabilized https://github.com/aquasecurity/tracee/issues/2870

**Comment by yanivagman** [comment]
Closing this epic with two items complete.
We can follow the other two items in their own issues
