### ISSUE TITLE
Tracee API server

### ISSUE THREAD

**Issue by yanivagman** [aquasecurity/tracee#2991]
This issue was already discussed in previous issues (#636, #1726), however, Tracee recently changed its architecture to be based on one binary and introduced policies which affects the way this API server should look like.

The goal is simple - allow configuring Tracee in runtime. In addition, the server may expose other functionalities in the future, such as getting statistics from Tracee and a stream of the events output.

To breakdown the work, the following steps should be taken (a separate issue can be opened for each):
- [x] **Define an API that will be exposed by Tracee**. The API shuold allow adding/removing/modifiying policies in runtime, getting statistics, and potentially getting a stream of events
- [x] **Map required changes**. Dynamically changing policies in runtime will require a lot of changes, such as adding/remvoing events in runtime, updating bpf maps, attaching events to probes and more. Also, we will need to invalidate some caches (e.g. the matched_scopes field in the bpf task_info_map will need to be invalidated) - we need to map all the required changes and think about the design
- [x] **Implementing the API**. After thinking about the API and required changes, we can start moving to the dirty part. This part will need to be broken into steps, according to the design we got from the previous steps.
- [x] **Implementing the server**  (probably using GRPC), which will use the API we implemented in the previous step

**Comment by josedonizetti** [comment]
As this issue is an EPIC which will probably exist for a couple releases, I've created a issue for the API v1 we want to release on 0.17.0 -> https://github.com/aquasecurity/tracee/issues/3208

**Comment by yanivagman** [comment]
Since we already implemented a first iteration of the API in #3208 and we have a dedicated issue for dynamic policy modification in #3239, I think we can close this issue
