### ISSUE TITLE
Support dynamic loading of policies

### ISSUE THREAD

**Issue by geyslan** [aquasecurity/tracee#3239]
Context: https://github.com/aquasecurity/tracee/pull/3209#issuecomment-1591171759

- [x] #3469
  - [x] `populateBPFMaps()` `events_map` logic
  - [x] `initBPF()` `ProcessTreeFilter` logic
- [x] #3731
- [x] #3805
- [ ] Fixes
  - [ ] Snapshots Pruning and Inner Map creation rollback
    References:
    - https://github.com/aquasecurity/tracee/issues/4019#issuecomment-2118124368
    - #3912
  - [ ] Free GetBTFFDByID() resources - [Reference](https://github.com/aquasecurity/tracee/issues/4019#issuecomment-2118124368)
- [ ] Refactorings (required)
  - [x] https://github.com/aquasecurity/tracee/pull/3906
  - [x] https://github.com/aquasecurity/tracee/pull/3955
  - [x] https://github.com/aquasecurity/tracee/pull/3956
  - [x] https://github.com/aquasecurity/tracee/pull/3963
  - [x] https://github.com/aquasecurity/tracee/pull/3966
  - [x] https://github.com/aquasecurity/tracee/pull/3979
  - [x] https://github.com/aquasecurity/tracee/pull/3997
  - [ ] Matched Rules (instead of Policies - https://github.com/aquasecurity/tracee/pull/4484
  - [ ] PolicyManager API Refactor - https://github.com/aquasecurity/tracee/pull/4484
- [ ] ...

**Comment by geyslan** [comment]
Open this [PR](https://github.com/aquasecurity/tracee/pull/3249) as a PoC for discussion. It raised deadlocks.

**Comment by geyslan** [comment]
#3250 uses snapshots (circular buffer).

**Comment by yanivagman** [comment]
@geyslan I thought about the following API to be added:

AddPolicy(Policy) error
UpdatePolicy(Policy) error
DeletePolicy(Policy) error
ListPolicies()

WDYT?

**Comment by geyslan** [comment]
@yanivagman considering that this API should be to PolicyManager, perhaps:

DeletePolicy(name) error

instead of the policyObject as parameter.

**Comment by yanivagman** [comment]
> @yanivagman considering that this API should be to PolicyManager, perhaps:
> 
> DeletePolicy(name) error
> 
> instead of the policyObject as parameter.

Yes, I agree.
I thought about the following API functions:
`AddPolicy(policy) error` - Add a new policy to Tracee. A full policy (struct parsed from the yaml) is provided. If a policy with the same name already exists, an error should be returned.
`UpdatePolicy(policy) error` - for now, we won't support providing deltas in the update, and full description of the new policy (as a struct) must be provided. We should decide what to do in case a policy with the same name doesn't exist. We can either return an error or simply add the new policy.
`DeletePolicy(name) error`
`ListPolicies() policies`

WDYT?
